# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aster/protos/bidirectional_rnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aster.protos import rnn_cell_pb2 as aster_dot_protos_dot_rnn__cell__pb2
from aster.protos import hyperparams_pb2 as aster_dot_protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aster/protos/bidirectional_rnn.proto',
  package='aster.protos',
  syntax='proto2',
  serialized_pb=_b('\n$aster/protos/bidirectional_rnn.proto\x12\x0c\x61ster.protos\x1a\x1b\x61ster/protos/rnn_cell.proto\x1a\x1e\x61ster/protos/hyperparams.proto\"\x81\x02\n\x10\x42idirectionalRnn\x12\x14\n\x06static\x18\x01 \x01(\x08:\x04true\x12-\n\x0e\x66w_bw_rnn_cell\x18\x02 \x01(\x0b\x32\x15.aster.protos.RnnCell\x12\x32\n\x0frnn_regularizer\x18\x03 \x01(\x0b\x32\x19.aster.protos.Regularizer\x12\x1b\n\x10num_output_units\x18\x04 \x01(\x05:\x01\x30\x12\x31\n\x0e\x66\x63_hyperparams\x18\x05 \x01(\x0b\x32\x19.aster.protos.Hyperparams\x12$\n\x15summarize_activations\x18\x06 \x01(\x08:\x05\x66\x61lse')
  ,
  dependencies=[aster_dot_protos_dot_rnn__cell__pb2.DESCRIPTOR,aster_dot_protos_dot_hyperparams__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BIDIRECTIONALRNN = _descriptor.Descriptor(
  name='BidirectionalRnn',
  full_name='aster.protos.BidirectionalRnn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='static', full_name='aster.protos.BidirectionalRnn.static', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fw_bw_rnn_cell', full_name='aster.protos.BidirectionalRnn.fw_bw_rnn_cell', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rnn_regularizer', full_name='aster.protos.BidirectionalRnn.rnn_regularizer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_output_units', full_name='aster.protos.BidirectionalRnn.num_output_units', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fc_hyperparams', full_name='aster.protos.BidirectionalRnn.fc_hyperparams', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='aster.protos.BidirectionalRnn.summarize_activations', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=373,
)

_BIDIRECTIONALRNN.fields_by_name['fw_bw_rnn_cell'].message_type = aster_dot_protos_dot_rnn__cell__pb2._RNNCELL
_BIDIRECTIONALRNN.fields_by_name['rnn_regularizer'].message_type = aster_dot_protos_dot_hyperparams__pb2._REGULARIZER
_BIDIRECTIONALRNN.fields_by_name['fc_hyperparams'].message_type = aster_dot_protos_dot_hyperparams__pb2._HYPERPARAMS
DESCRIPTOR.message_types_by_name['BidirectionalRnn'] = _BIDIRECTIONALRNN

BidirectionalRnn = _reflection.GeneratedProtocolMessageType('BidirectionalRnn', (_message.Message,), dict(
  DESCRIPTOR = _BIDIRECTIONALRNN,
  __module__ = 'aster.protos.bidirectional_rnn_pb2'
  # @@protoc_insertion_point(class_scope:aster.protos.BidirectionalRnn)
  ))
_sym_db.RegisterMessage(BidirectionalRnn)


# @@protoc_insertion_point(module_scope)
