# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aster/protos/label_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aster/protos/label_map.proto',
  package='aster.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x61ster/protos/label_map.proto\x12\x0c\x61ster.protos\"i\n\x08LabelMap\x12\x31\n\rcharacter_set\x18\x01 \x01(\x0b\x32\x1a.aster.protos.CharacterSet\x12\x17\n\x0clabel_offset\x18\x02 \x01(\x03:\x01\x30\x12\x11\n\tunk_label\x18\x03 \x01(\x03\"\xd9\x01\n\x0c\x43haracterSet\x12\x15\n\ttext_file\x18\x01 \x01(\t:\x00H\x00\x12\x17\n\x0btext_string\x18\x02 \x01(\t:\x00H\x00\x12H\n\x0c\x62uilt_in_set\x18\x03 \x01(\x0e\x32%.aster.protos.CharacterSet.BuiltInSet:\tLOWERCASEH\x00\"?\n\nBuiltInSet\x12\r\n\tLOWERCASE\x10\x00\x12\x0c\n\x08\x41LLCASES\x10\x01\x12\x14\n\x10\x41LLCASES_SYMBOLS\x10\x02\x42\x0e\n\x0csource_oneof')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CHARACTERSET_BUILTINSET = _descriptor.EnumDescriptor(
  name='BuiltInSet',
  full_name='aster.protos.CharacterSet.BuiltInSet',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOWERCASE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALLCASES', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALLCASES_SYMBOLS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=292,
  serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_CHARACTERSET_BUILTINSET)


_LABELMAP = _descriptor.Descriptor(
  name='LabelMap',
  full_name='aster.protos.LabelMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='character_set', full_name='aster.protos.LabelMap.character_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_offset', full_name='aster.protos.LabelMap.label_offset', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unk_label', full_name='aster.protos.LabelMap.unk_label', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=151,
)


_CHARACTERSET = _descriptor.Descriptor(
  name='CharacterSet',
  full_name='aster.protos.CharacterSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_file', full_name='aster.protos.CharacterSet.text_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_string', full_name='aster.protos.CharacterSet.text_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='built_in_set', full_name='aster.protos.CharacterSet.built_in_set', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHARACTERSET_BUILTINSET,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='source_oneof', full_name='aster.protos.CharacterSet.source_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=154,
  serialized_end=371,
)

_LABELMAP.fields_by_name['character_set'].message_type = _CHARACTERSET
_CHARACTERSET.fields_by_name['built_in_set'].enum_type = _CHARACTERSET_BUILTINSET
_CHARACTERSET_BUILTINSET.containing_type = _CHARACTERSET
_CHARACTERSET.oneofs_by_name['source_oneof'].fields.append(
  _CHARACTERSET.fields_by_name['text_file'])
_CHARACTERSET.fields_by_name['text_file'].containing_oneof = _CHARACTERSET.oneofs_by_name['source_oneof']
_CHARACTERSET.oneofs_by_name['source_oneof'].fields.append(
  _CHARACTERSET.fields_by_name['text_string'])
_CHARACTERSET.fields_by_name['text_string'].containing_oneof = _CHARACTERSET.oneofs_by_name['source_oneof']
_CHARACTERSET.oneofs_by_name['source_oneof'].fields.append(
  _CHARACTERSET.fields_by_name['built_in_set'])
_CHARACTERSET.fields_by_name['built_in_set'].containing_oneof = _CHARACTERSET.oneofs_by_name['source_oneof']
DESCRIPTOR.message_types_by_name['LabelMap'] = _LABELMAP
DESCRIPTOR.message_types_by_name['CharacterSet'] = _CHARACTERSET

LabelMap = _reflection.GeneratedProtocolMessageType('LabelMap', (_message.Message,), dict(
  DESCRIPTOR = _LABELMAP,
  __module__ = 'aster.protos.label_map_pb2'
  # @@protoc_insertion_point(class_scope:aster.protos.LabelMap)
  ))
_sym_db.RegisterMessage(LabelMap)

CharacterSet = _reflection.GeneratedProtocolMessageType('CharacterSet', (_message.Message,), dict(
  DESCRIPTOR = _CHARACTERSET,
  __module__ = 'aster.protos.label_map_pb2'
  # @@protoc_insertion_point(class_scope:aster.protos.CharacterSet)
  ))
_sym_db.RegisterMessage(CharacterSet)


# @@protoc_insertion_point(module_scope)
