# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aster/protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aster.protos import feature_extractor_pb2 as aster_dot_protos_dot_feature__extractor__pb2
from aster.protos import predictor_pb2 as aster_dot_protos_dot_predictor__pb2
from aster.protos import spatial_transformer_pb2 as aster_dot_protos_dot_spatial__transformer__pb2
from aster.protos import loss_pb2 as aster_dot_protos_dot_loss__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aster/protos/model.proto',
  package='aster.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x61ster/protos/model.proto\x12\x0c\x61ster.protos\x1a$aster/protos/feature_extractor.proto\x1a\x1c\x61ster/protos/predictor.proto\x1a&aster/protos/spatial_transformer.proto\x1a\x17\x61ster/protos/loss.proto\"s\n\x05Model\x12[\n\"multi_predictors_recognition_model\x18\x01 \x01(\x0b\x32-.aster.protos.MultiPredictorsRecognitionModelH\x00\x42\r\n\x0bmodel_oneof\"\x99\x02\n\x1fMultiPredictorsRecognitionModel\x12=\n\x13spatial_transformer\x18\x01 \x01(\x0b\x32 .aster.protos.SpatialTransformer\x12\x39\n\x11\x66\x65\x61ture_extractor\x18\x02 \x01(\x0b\x32\x1e.aster.protos.FeatureExtractor\x12*\n\tpredictor\x18\x03 \x03(\x0b\x32\x17.aster.protos.Predictor\x12#\n\x14keypoint_supervision\x18\x04 \x01(\x08:\x05\x66\x61lse\x12+\n\x0fregression_loss\x18\x05 \x01(\x0b\x32\x12.aster.protos.Loss')
  ,
  dependencies=[aster_dot_protos_dot_feature__extractor__pb2.DESCRIPTOR,aster_dot_protos_dot_predictor__pb2.DESCRIPTOR,aster_dot_protos_dot_spatial__transformer__pb2.DESCRIPTOR,aster_dot_protos_dot_loss__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='aster.protos.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_predictors_recognition_model', full_name='aster.protos.Model.multi_predictors_recognition_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='model_oneof', full_name='aster.protos.Model.model_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=175,
  serialized_end=290,
)


_MULTIPREDICTORSRECOGNITIONMODEL = _descriptor.Descriptor(
  name='MultiPredictorsRecognitionModel',
  full_name='aster.protos.MultiPredictorsRecognitionModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spatial_transformer', full_name='aster.protos.MultiPredictorsRecognitionModel.spatial_transformer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='aster.protos.MultiPredictorsRecognitionModel.feature_extractor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='predictor', full_name='aster.protos.MultiPredictorsRecognitionModel.predictor', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keypoint_supervision', full_name='aster.protos.MultiPredictorsRecognitionModel.keypoint_supervision', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='regression_loss', full_name='aster.protos.MultiPredictorsRecognitionModel.regression_loss', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=574,
)

_MODEL.fields_by_name['multi_predictors_recognition_model'].message_type = _MULTIPREDICTORSRECOGNITIONMODEL
_MODEL.oneofs_by_name['model_oneof'].fields.append(
  _MODEL.fields_by_name['multi_predictors_recognition_model'])
_MODEL.fields_by_name['multi_predictors_recognition_model'].containing_oneof = _MODEL.oneofs_by_name['model_oneof']
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['spatial_transformer'].message_type = aster_dot_protos_dot_spatial__transformer__pb2._SPATIALTRANSFORMER
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['feature_extractor'].message_type = aster_dot_protos_dot_feature__extractor__pb2._FEATUREEXTRACTOR
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['predictor'].message_type = aster_dot_protos_dot_predictor__pb2._PREDICTOR
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['regression_loss'].message_type = aster_dot_protos_dot_loss__pb2._LOSS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['MultiPredictorsRecognitionModel'] = _MULTIPREDICTORSRECOGNITIONMODEL

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'aster.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:aster.protos.Model)
  ))
_sym_db.RegisterMessage(Model)

MultiPredictorsRecognitionModel = _reflection.GeneratedProtocolMessageType('MultiPredictorsRecognitionModel', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPREDICTORSRECOGNITIONMODEL,
  __module__ = 'aster.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:aster.protos.MultiPredictorsRecognitionModel)
  ))
_sym_db.RegisterMessage(MultiPredictorsRecognitionModel)


# @@protoc_insertion_point(module_scope)
