# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aster/protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aster.protos import train_pb2 as aster_dot_protos_dot_train__pb2
from aster.protos import eval_pb2 as aster_dot_protos_dot_eval__pb2
from aster.protos import input_reader_pb2 as aster_dot_protos_dot_input__reader__pb2
from aster.protos import model_pb2 as aster_dot_protos_dot_model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aster/protos/pipeline.proto',
  package='aster.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x61ster/protos/pipeline.proto\x12\x0c\x61ster.protos\x1a\x18\x61ster/protos/train.proto\x1a\x17\x61ster/protos/eval.proto\x1a\x1f\x61ster/protos/input_reader.proto\x1a\x18\x61ster/protos/model.proto\"\x8a\x02\n\x17TrainEvalPipelineConfig\x12\"\n\x05model\x18\x01 \x01(\x0b\x32\x13.aster.protos.Model\x12/\n\x0ctrain_config\x18\x02 \x01(\x0b\x32\x19.aster.protos.TrainConfig\x12\x35\n\x12train_input_reader\x18\x03 \x03(\x0b\x32\x19.aster.protos.InputReader\x12-\n\x0b\x65val_config\x18\x04 \x01(\x0b\x32\x18.aster.protos.EvalConfig\x12\x34\n\x11\x65val_input_reader\x18\x05 \x01(\x0b\x32\x19.aster.protos.InputReader')
  ,
  dependencies=[aster_dot_protos_dot_train__pb2.DESCRIPTOR,aster_dot_protos_dot_eval__pb2.DESCRIPTOR,aster_dot_protos_dot_input__reader__pb2.DESCRIPTOR,aster_dot_protos_dot_model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINEVALPIPELINECONFIG = _descriptor.Descriptor(
  name='TrainEvalPipelineConfig',
  full_name='aster.protos.TrainEvalPipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='aster.protos.TrainEvalPipelineConfig.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='aster.protos.TrainEvalPipelineConfig.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_input_reader', full_name='aster.protos.TrainEvalPipelineConfig.train_input_reader', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='aster.protos.TrainEvalPipelineConfig.eval_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_input_reader', full_name='aster.protos.TrainEvalPipelineConfig.eval_input_reader', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=422,
)

_TRAINEVALPIPELINECONFIG.fields_by_name['model'].message_type = aster_dot_protos_dot_model__pb2._MODEL
_TRAINEVALPIPELINECONFIG.fields_by_name['train_config'].message_type = aster_dot_protos_dot_train__pb2._TRAINCONFIG
_TRAINEVALPIPELINECONFIG.fields_by_name['train_input_reader'].message_type = aster_dot_protos_dot_input__reader__pb2._INPUTREADER
_TRAINEVALPIPELINECONFIG.fields_by_name['eval_config'].message_type = aster_dot_protos_dot_eval__pb2._EVALCONFIG
_TRAINEVALPIPELINECONFIG.fields_by_name['eval_input_reader'].message_type = aster_dot_protos_dot_input__reader__pb2._INPUTREADER
DESCRIPTOR.message_types_by_name['TrainEvalPipelineConfig'] = _TRAINEVALPIPELINECONFIG

TrainEvalPipelineConfig = _reflection.GeneratedProtocolMessageType('TrainEvalPipelineConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINEVALPIPELINECONFIG,
  __module__ = 'aster.protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:aster.protos.TrainEvalPipelineConfig)
  ))
_sym_db.RegisterMessage(TrainEvalPipelineConfig)


# @@protoc_insertion_point(module_scope)
